default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: dach3r
  password: 123456

development:
  <<: *default
  database: Work_To_Do_development

test:
  <<: *default
  database: work_to_do_test
